name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *" # once a day at midnight UTC
  workflow_dispatch: # lets you run it manually from the Actions tab

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: tomas-og
          BRANCH_NAME: "main"
